# Generated by Django 3.2.9 on 2021-12-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
