# Generated by Django 3.2.9 on 2021-12-14 13:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ads_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
