# Generated by Django 3.2.9 on 2021-12-14 13:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ads_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='body2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='text',
            field=models.TextField(),
        ),
    ]
