# Generated by Django 3.2.9 on 2021-12-15 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20211214_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='body',
        ),
    ]
