# Generated by Django 3.2.9 on 2021-12-15 09:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_ads_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='body',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='body2',
        ),
        migrations.AlterField(
            model_name='ads',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
