# Generated by Django 4.1.4 on 2023-01-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_auto_20211215_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Обявлении'},
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Отклик', 'verbose_name_plural': 'Отклики'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
